name = "archaic_terminal"
description = "Terminal setup for other libraries"
version = "0.0.1"

authors = ["Paul Jarrett"]
maintainers = ["Paul Jarrett <jarrett.paul.young@gmail.com>"]
maintainers-logins = ["pyjarrett"]
licenses = "Apache-2.0"
tags = ["terminal", "command-line", "console"]

project-files = ["archaic_terminal.gpr"]

[gpr-externals]
Mode = ["debug", "optimize"]

[gpr-set-externals.'case(os)']
windows = { Platform = "windows" }
linux = { Platform = "linux" }
macos = { Platform = "macos" }

[available.'case(os)']
linux = true
windows = true
macos = false
